apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-devops-app
  labels:
    app: aws-devops-app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: aws-devops-app

  template:
    metadata:
      labels:
        app: aws-devops-app

    spec:
      containers:
        - name: aws-devops-app
          image: 839084984521.dkr.ecr.ap-south-1.amazonaws.com/aws-devops-project:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
